name: code_prac_hwsa2021
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip>=21.1.3
  - matplotlib>=1.5.1
  - scipy>=0.17.1
  - numba>=0.53.1
  - Sphinx>=2.3.1
  - line_profiler>=3.3.0
  - black>=21.5b2
  - isort>=5.9.1
  - pytest>=6.2.4
  - pytest-regtest>=1.3.2
  - pre-commit>=2.13.0
  - coverage>=5.5
